apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-test-script
  namespace: fastfood-app
data:
  test.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export let options = {
      vus: 1000, // Número de usuários virtuais
      duration: '130s', // Duração do teste
    };

    export default function () {
      let res = http.get('http://fastfood-api-service:8080//customers/012.438.426-95');
      check(res, { 'status is 200': (r) => r.status === 200 });
      sleep(1);
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
  namespace: fastfood-app
spec:
  template:
    spec:
      containers:
        - name: k6
          image: grafana/k6:latest
          args: ["run", "/scripts/test.js"]
          volumeMounts:
            - name: k6-scripts
              mountPath: /scripts
      restartPolicy: Never
      volumes:
        - name: k6-scripts
          configMap:
            name: k6-test-script
  backoffLimit: 0