apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-api-deployment
  namespace: fastfood-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastfood-api
  template:
    metadata:
      labels:
        app: fastfood-api
    spec:
      containers:
        - name: fastfood-api
          image: hmouraf/fastfood:tech_fase2
#          image: soat-tech-challenge-fast-food-app:tech_fase2
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "800Mi" # Mínimo de memória garantida
              cpu: "250m"      # Mínimo de CPU garantida (0.25 cores)
            limits:
              memory: "1G" # Máximo de memória que o container pode usar
              cpu: "512m"      # Máximo de CPU que o container pode usar (0.5 cores)
          envFrom:
            - configMapRef:
                name: fastfood-api-configmap
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fastfood-api-secrets
                  key: DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastfood-api-secrets
                  key: DATASOURCE_PASSWORD
          livenessProbe:
            httpGet:
              path: /swagger-ui/index.html
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 60

          readinessProbe:
            httpGet:
              path: /swagger-ui/index.html
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 60
---

